### ISSUE TITLE
Cannot insert duplicate key row in object 'Build.tbl_Artifact' with unique index 'IX_Build_tbl_Artifact_BuildId_ArtifactNameId'. The duplicate key value is (1, 161, 7313, 192).

### ISSUE THREAD

**Issue by AtkinsonHD** [dependency-check/azuredevops#100]
Hi keep getting an issue where we get duplicates in the build.tbl_artififact but I have no idea why. 

```
Dependency Check completed with exit code 0.
Dependency Check reports:
 'C:\\agentA\\_work\\2\\TestResults\\dependency-check\\dependency-check-report.html',
 'C:\\agentA\\_work\\2\\TestResults\\dependency-check\\dependency-check-report.json',
  'C:\\agentA\\_work\\2\\TestResults\\dependency-check\\dependency-check-report.xml' ]
 Dependency Check succeeded with message "Dependency Check succeeded"
Ending Dependency Check...
 ##[section]Async Command Start: Upload Artifact
 Uploading 1 files
File upload succeed.
 'C:\agentA\_work\2\TestResults\dependency-check\dependency-check-report.html' to file container: '#/36563/dependency-check'
 ##[section]Async Command End: Upload Artifact
 ##[error]Cannot insert duplicate key row in object 'Build.tbl_Artifact' with unique index 'IX_Build_tbl_Artifact_BuildId_ArtifactNameId'. The duplicate key value is (1, 161, 7313, 192).
 ##[section]Async Command Start: Upload Artifact
Uploading 1 files
 File upload succeed.
 Upload 'C:\agentA\_work\2\TestResults\dependency-check\dependency-check-report.json' to file container: '#/36563/dependency-check'
 Associated artifact 1627 with build 7313
 ##[section]Async Command End: Upload Artifact
 ##[section]Async Command Start: Upload Artifact
 Uploading 1 files
File upload succeed.
 Upload 'C:\agentA\_work\2\TestResults\dependency-check\dependency-check-report.xml' to file container: '#/36563/dependency-check'
 Associated artifact 1627 with build 7313
 ##[section]Async Command End: Upload Artifact
 ##[section]Finishing: Dependency Check
```

Spotted my versions has "Report Filename" - Report output filename. Will set the report output name in 'reportsDirectory' to specified filename. Will not work if format is ALL, or multiple formats are supplied to the 'format' parameter. Filename must have an extension or dependency-check will assume it is a path. 

Can this be used to alter something?
We actually upload our reports directly to sonarcube so we dont actually need them as atifacts, so could this feature be disabled with an override?

**Comment by jtbatzer** [comment]
I also received this error today
```
##[debug]File: 'E:\TFSBuild_Directory\39\TestResults\dependency-check\dependency-check-report.html' took 203 milliseconds to finish upload
##[debug]Detail upload trace for file: dependency-check/dependency-check-report.html
##[debug]File 'dependency-check/dependency-check-report.html' will be uploaded in one chunk.
##[debug]Attempt '1' for uploading chunk '1' of file 'dependency-check/dependency-check-report.html'.
##[debug]Generate new HttpRequest for uploading file 'dependency-check/dependency-check-report.html', chunk '1' of '1'.
##[debug]Start uploading file 'dependency-check/dependency-check-report.html' to server, chunk '1'.
##[debug]Finished upload chunk '1' of file 'dependency-check/dependency-check-report.html', elapsed 132 (ms), response code 'Created'.
File upload succeed.
Upload 'E:\TFSBuild_Directory\39\TestResults\dependency-check\dependency-check-report.html' to file container: '#/28444/dependency-check'
Async Command End: Upload Artifact
##[error]Cannot insert duplicate key row in object 'Build.tbl_Artifact' with unique index 'IX_Build_tbl_Artifact_BuildId_ArtifactNameId'. The duplicate key value is (1, 99, 8537, 15).
##[debug]Microsoft.VisualStudio.Services.Common.VssServiceException: Cannot insert duplicate key row in object 'Build.tbl_Artifact' with unique index 'IX_Build_tbl_Artifact_BuildId_ArtifactNameId'. The duplicate key value is (1, 99, 8537, 15).
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
   at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientCompatBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken, Func`3 processResponse)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildServer.AssociateArtifactAsync(Int32 buildId, Guid projectId, String name, String jobId, String type, String data, Dictionary`2 propertiesDictionary, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.ArtifactCommandExtensionUtil.UploadArtifactAsync(IAsyncCommandContext context, VssConnection connection, Guid projectId, Int64 containerId, String containerPath, Int32 buildId, String name, String jobId, Dictionary`2 propertiesDictionary, String source, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.AsyncCommandContext.WaitAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
Async Command Start: Upload Artifact

```
Any progress on this issue?

**Comment by Jirka-mse** [comment]
Any progress on this issue? I get the same error while compile and upload artifaces with ALOps

**Comment by LucaBlackDragon** [comment]
Same issue randomly happens to me too. It doesn't seem related to scan results though.

And I agree with @jtbatzer, it would be great to be able to opt-out of artifacts upload, or to choose the artifact name.
For example, one may want to name the artifact "CodeAnalysisLogs" because it's the expected name of [this Microsoft extension](https://marketplace.visualstudio.com/items?itemName=sariftools.scans) that adds a Scans tab to the pipeline page, as proposed in PR #136.

But I'm afraid this repository is no longer maintained :(
